-- MySQL Script generated by MySQL Workbench
-- jue 12 nov 2020 10:38:05 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Localidad` VARCHAR(60) NOT NULL,
  `Concejal` VARCHAR(60) NOT NULL,
  `Municipio` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  `Año de construción` INT NOT NULL,
  `Localidad` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Número`, `Calle`),
  CONSTRAINT `Localidad`
    FOREIGN KEY (`Localidad`)
    REFERENCES `mydb`.`Zona` (`Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda Unifamiliar` (
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  `Año de construción` INT NOT NULL,
  `Localidad` VARCHAR(60) NOT NULL,
  `Número de habitaciones` INT NOT NULL,
  PRIMARY KEY (`Número`, `Calle`),
  CONSTRAINT `Localida`
    FOREIGN KEY (`Localidad`)
    REFERENCES `mydb`.`Zona` (`Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(2) NOT NULL,
  `Número de habitaciones` INT NOT NULL,
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Planta`, `Letra`, `Número`, `Calle`),
  CONSTRAINT `Número`
    FOREIGN KEY (`Número`)
    REFERENCES `mydb`.`Bloque` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Fecha de nacimiento` VARCHAR(45) NOT NULL,
  `Vivienda Unifamiliar_Número` INT NOT NULL,
  `Vivienda Unifamiliar_Calle` VARCHAR(60) NOT NULL,
  `Piso_Planta` INT NOT NULL,
  `Piso_Letra` VARCHAR(2) NOT NULL,
  `Piso_Número` INT NOT NULL,
  `Piso_Calle` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`DNI`, `Vivienda Unifamiliar_Número`, `Vivienda Unifamiliar_Calle`, `Piso_Planta`, `Piso_Letra`, `Piso_Número`, `Piso_Calle`),
  CONSTRAINT `fk_Persona_Vivienda Unifamiliar1`
    FOREIGN KEY (`Vivienda Unifamiliar_Número` , `Vivienda Unifamiliar_Calle`)
    REFERENCES `mydb`.`Vivienda Unifamiliar` (`Número` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Piso1`
    FOREIGN KEY (`Piso_Planta` , `Piso_Letra` , `Piso_Número` , `Piso_Calle`)
    REFERENCES `mydb`.`Piso` (`Planta` , `Letra` , `Número` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
